{"update":{"14.10":[{"package":"python-dbusmock","version":"0.11.4-1ubuntu1"},{"package":"python3-dbusmock","version":"0.11.4-1ubuntu1"}],"15.04":[{"version":"0.14-1ubuntu2","package":"python-dbusmock"},{"package":"python3-dbusmock","version":"0.14-1ubuntu2"}],"14.04":[{"version":"0.10.1-1ubuntu1","package":"python-dbusmock"},{"package":"python3-dbusmock","version":"0.10.1-1ubuntu1"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","date":"May 21, 2015","threat":["A local attacker could possibly use this issue to execute arbitrary code.."],"usn":"USN-2618-1","CVEs":["CVE-2015-1326"],"info":"python-dbusmock vulnerability"}