{"threat":["A remote unauthenticated attacker could exploit this using the Nova API to cause a denial of service via resource exhaustion."],"special":"The problem can be corrected by updating your system to the following package versions:\n  python-nova\n2012.2.1+stable-20121212-a99a802e-0ubuntu1.2\nUbuntu 12.04 LTS:\n  python-nova\n2012.1.3+stable-20120827-4d2a4afe-0ubuntu1.2\nUbuntu 11.10:\n  python-nova                     2011.3-0ubuntu6.12\nIn general, a standard system update will make all the necessary changes.","update":{},"date":"February 21, 2013","CVEs":["CVE-2013-1664"],"info":"nova vulnerability","usn":"USN-1734-1"}