{"date":"September 10, 2012","usn":"USN-1560-1","CVEs":["CVE-2012-3442","CVE-2012-3443","CVE-2012-3444"],"info":"python-django vulnerabilities","special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","threat":["If a user were tricked into opening a specially crafted URL, an attacker could possibly exploit this to conduct cross-site scripting (XSS) attacks.","A remote attacker could use this flaw to cause the server to consume memory, leading to a denial of service.","A remote attacker could use this flaw to cause the server to consume resources, leading to a denial of service."],"update":{"11.10":[{"version":"1.3-2ubuntu1.3","package":"python-django"}],"11.04":[{"package":"python-django","version":"1.2.5-1ubuntu1.2"}],"10.04":[{"version":"1.1.1-2ubuntu1.5","package":"python-django"}],"12.04":[{"version":"1.3.1-4ubuntu1.2","package":"python-django"}]}}