{"date":"October 24, 2012","update":{"10.04":[{"package":"python3.1","version":"3.1.2-0ubuntu3.2"},{"package":"python3.1-minimal","version":"3.1.2-0ubuntu3.2"}],"11.04":[{"package":"python3.1","version":"3.1.3-1ubuntu1.2"},{"version":"3.1.3-1ubuntu1.2","package":"python3.1-minimal"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","usn":"USN-1616-1","CVEs":["CVE-2008-5983","CVE-2010-1634","CVE-2010-2089","CVE-2011-4944","CVE-2012-0845","CVE-2012-1150","CVE-2012-2135"],"threat":["A local attacker with write access to the current working directory could exploit this to execute arbitrary code.","If a user or automatated system were tricked into opening a crafted audio file, an attacker could cause a denial of service via application crash.","A local attacker could exploit this to obtain sensitive information.","A remote attacker could exploit this to cause a denial of service via excessive CPU utilization.","An attacker could cause a denial of service under certian circumstances.","An attacker could exploit this to cause a denial of service via memory corruption."],"info":"python3.1 vulnerabilities"}