{"update":{"12.10":[{"package":"python2.7","version":"2.7.3-5ubuntu4.3"},{"package":"python2.7-minimal","version":"2.7.3-5ubuntu4.3"}],"13.04":[{"version":"2.7.4-2ubuntu3.2","package":"python2.7"},{"version":"2.7.4-2ubuntu3.2","package":"python2.7-minimal"}],"12.04":[{"package":"python2.7","version":"2.7.3-0ubuntu3.4"},{"version":"2.7.3-0ubuntu3.4","package":"python2.7-minimal"}]},"threat":["An attacker could exploit this to cause Python to consume resources, resulting in a denial of service.","An attacker could exploit this to perform a man in the middle attack to view sensitive information or alter encrypted communications."],"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","info":"python2.7 vulnerabilities","CVEs":["CVE-2013-2099","CVE-2013-4238"],"usn":"USN-1983-1","date":"October 01, 2013"}