{"CVEs":["CVE-2012-4520","CVE-2013-0305","CVE-2013-0306","CVE-2013-1664","CVE-2013-1665"],"threat":["An attacker could exploit this to generate and display arbitrary URLs to users.","An attacker could use this flaw to cause Django to consume memory, resulting in a denial of service.","An attacker could use this flaw to perform entity-expansion and external-entity/DTD attacks."],"date":"March 07, 2013","info":"python-django vulnerabilities","usn":"USN-1757-1","update":{"10.04":[{"package":"python-django","version":"1.1.1-2ubuntu1.8"}],"12.10":[{"package":"python-django","version":"1.4.1-2ubuntu0.3"}],"11.10":[{"version":"1.3-2ubuntu1.6","package":"python-django"}],"12.04":[{"package":"python-django","version":"1.3.1-4ubuntu1.6"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes."}