{"info":"python-django vulnerabilities","threat":["A remote attacker could exploit this to modify sessions.","This could be exploited by a remote attacker to cause a denial of service via resource exhaustion.","A remote attacker could exploit this to conduct host header cache poisoning attacks via a crafted request."],"CVEs":["CVE-2011-4136","CVE-2011-4137","CVE-2011-4138","CVE-2011-4139"],"usn":"USN-1297-1","update":{"11.10":[{"package":"python-django","version":"1.3-2ubuntu1.1"}],"10.10":[{"version":"1.2.3-1ubuntu0.2.10.10.3","package":"python-django"}],"11.04":[{"version":"1.2.5-1ubuntu1.1","package":"python-django"}],"10.04":[{"version":"1.1.1-2ubuntu1.4","package":"python-django"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","date":"December 09, 2011"}